FROM oven/bun:1.1-slim

WORKDIR /app

COPY package.json ./
COPY prisma ./prisma/

RUN bun install
RUN bunx prisma generate

COPY . .

RUN bunx prisma migrate deploy

RUN bun run seed || true

EXPOSE 3001

CMD ["bun", "run", "start"]