FROM oven/bun:1.1-slim

WORKDIR /app

COPY package.json ./
COPY prisma ./prisma/

RUN bun install
RUN bunx prisma generate

COPY . .

EXPOSE 3001

CMD ["sh", "-c", "bunx prisma migrate deploy && bun run seed && bun run start"]